/**
 * 创建侧边栏可以让您：
 - 创建有序的文档组
 - 为每个文档组渲染侧边栏
 - 提供上一页/下一页导航

 侧边栏可以从文件系统生成，或在此处明确定义。

 您可以创建任意数量的侧边栏。
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // 默认情况下，Docusaurus 从 docs 文件夹结构生成侧边栏
  tutorialSidebar: [{ type: "autogenerated", dirName: "." }],
  // 但您也可以手动创建侧边栏
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: '教程',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

module.exports = sidebars;